export interface Legend {
  name: string;
  description: string;
}

export interface LegendCategory {
  categoryName: string;
  legends: Legend[];
}

export const legendsData: LegendCategory[] = [
  {
    categoryName: "Mitolojik Efsaneler",
    legends: [
      { name: "Herkül'ün 12 Görevi", description: "Yarı tanrı Herkül'ün imkansız görünen görevlerini tamamla." },
      { name: "Truva Savaşı", description: "Aşil ve Hektor gibi kahramanların olduğu efsanevi savaşa katıl." },
      { name: "Gılgamış Destanı", description: "Ölümsüzlüğü arayan Sümer kralı Gılgamış'ın maceralarını yaşa." },
      { name: "Ragnarok", description: "İskandinav tanrılarının kıyamet savaşında Odin ve Thor ile omuz omuza savaş." },
      { name: "Theseus ve Minotaur", description: "Girit'in labirentinde korkunç Minotaur'u bul ve alt et." },
      { name: "İason ve Altın Post", description: "Argo gemisiyle tehlikeli denizleri aş ve Altın Post'u ele geçir." },
      { name: "Osiris Miti", description: "Kardeşi Set tarafından öldürülen Mısır tanrısı Osiris'in yeniden doğuşuna tanıklık et." },
      { name: "Amaterasu'nun Mağarası", description: "Japon güneş tanrıçası Amaterasu'yu saklandığı mağaradan çıkarmaya yardım et." },
      { name: "Pandora'nın Kutusu", description: "Dünyaya salınan kötülüklerle dolu kutunun ardındaki sırrı ve umudu keşfet." },
      { name: "Kral Midas", description: "Dokunduğu her şeyi altına çeviren lanetli kralın trajedisini yaşa." },
      { name: "Ikarus'un Düşüşü", description: "Babası Daidalos'un yaptığı kanatlarla gökyüzüne yüksel, ama güneşe çok yaklaşma." },
      { name: "Medusa'nın Laneti", description: "Güzelliğiyle lanetlenen ve bakışlarıyla taşa çeviren Gorgon'un hikayesi." },
      { name: "Sisyphos'un Kayası", description: "Tanrıları kandıran kral Sisyphos'un sonsuz cezasına ortak ol." },
      { name: "Orpheus ve Eurydice", description: "Sevdiğini yeraltı dünyasından kurtarmak için lirini çal, ama asla arkana bakma." },
      { name: "Babil Kulesi", description: "Tanrıya ulaşmak için inşa edilen bu devasa kulenin yapımına ve yıkılışına şahit ol." },
      { name: "Odin'in Bilgelik Arayışı", description: "Bilgelik kuyusundan bir yudum almak için gözünü feda eden tanrının yolculuğu." },
      { name: "Arachne'nin Kibri", description: "Tanrıça Athena'ya dokumacılıkta meydan okuyan ölümlünün kaderini yaşa." },
      { name: "Perseus ve Andromeda", description: "Medusa'yı alt eden kahraman olarak, bir deniz canavarına kurban edilen prensesi kurtar." },
      { name: "Nuh Tufanı", description: "Tanrının emriyle dev bir gemi inşa et ve dünyayı kaplayan tufandan canlıları kurtar." },
      { name: "Ra'nın Güneş Teknesi", description: "Mısır güneş tanrısı Ra ile gökyüzünde ve yeraltında her gün süren yolculuğa çık." },
      { name: "Anubis ve Tartı Töreni", description: "Ölüler diyarında, kalbinin bir tüyden hafif olup olmadığını görmek için yargılan." },
      { name: "Loki'nin Hileleri", description: "İskandinav hile tanrısı olarak Asgard'ı karıştıracak entrikalar düzenle." },
      { name: "Romulus ve Remus", description: "Bir kurt tarafından büyütülen ikiz kardeşler olarak Roma şehrini kur." },
      { name: "Dainichi Nyorai'nin Işığı", description: "Japon Budizminde, evrenin merkezindeki Buda olarak aydınlanmaya çalış." },
      { name: "Maui'nin Oltası", description: "Polinezya'nın hileci kahramanı olarak adaları denizden çıkarmak için sihirli oltanı kullan." },
      { name: "Cu Chulainn'in Gazabı", description: "İrlanda'nın en büyük kahramanı olarak tek başına bir orduya karşı savaş." },
      { name: "Beowulf ve Grendel", description: "Bir bal likörü salonunu terörize eden canavar Grendel'i yenmek için yola çık." },
      { name: "Vainamoinen ve Sampo", description: "Fin ulusal destanı Kalevala'da, bolluk getiren sihirli Sampo'yu yap veya çal." },
      { name: "Kain ve Habil", description: "İnsanlık tarihinin ilk cinayetinde, kardeş kıskançlığının sonuçlarıyla yüzleş." },
      { name: "Yaratılış Efsaneleri", description: "Farklı kültürlerin (Yoruba, Hindu, Aborjin) dünyayı nasıl yarattığını deneyimle." },
      { name: "Kıyamet Efsaneleri", description: "Azteklerin Beş Güneşi veya Zerdüştlerin Frashokereti'si gibi son günleri yaşa." },
      { name: "Ejderhaların Kökeni", description: "Çin mitolojisinde, ejderhaların nasıl bilgelik ve güç sembolü haline geldiğini öğren." },
      { name: "Quetzalcoatl'ın Mirası", description: "Azteklerin tüylü yılan tanrısı olarak halkına bilgelik ve medeniyet getir." },
      { name: "Adem ve Havva", description: "Cennet Bahçesi'nde yasak meyveyi yemenin sonuçlarıyla yüzleş." },
    ],
  },
  {
    categoryName: "Türk ve Anadolu Efsaneleri",
    legends: [
      { name: "Ergenekon Destanı", description: "Demir dağı eriterek atalarına yeniden yol açan Göktürklerin lideri ol." },
      { name: "Şahmaran Efsanesi", description: "Yılanların kraliçesi Şahmaran'ın sırrını keşfet ve onu koru." },
      { name: "Ağrı Dağı Efsanesi", description: "Gülbahar ve çoban Ahmet'in trajik aşk hikayesinde kaderi değiştirmeye çalış." },
      { name: "Kız Kulesi Efsanesi", description: "Yılan kehanetinden kaçmak için kuleye kapatılan prensesin hikayesini yaşa." },
      { name: "Nasreddin Hoca", description: "Anadolu'nun bilge ve komik kahramanıyla fıkraları yaşa ve dersler çıkar." },
      { name: "Köroğlu Destanı", description: "Babasının intikamı için dağlara çıkan Ruşen Ali'nin adalet mücadelesine katıl." },
      { name: "Alkarısı Efsanesi", description: "Lohusa kadınların kabusu olan bu mitolojik varlıkla mücadele et." },
      { name: "Tepegöz", description: "Dede Korkut hikayelerindeki tek gözlü devi alt eden Basat'ın yanında ol." },
      { name: "Ferhat ile Şirin", description: "Aşkı için dağları delmesi gereken Ferhat'ın imkansız görevini üstlen." },
      { name: "Battal Gazi", description: "Bizans'a karşı savaşan efsanevi Arap komutanının kahramanlıklarına ortak ol." },
      { name: "Bozkurt Destanı", description: "Dişi bir kurt tarafından kurtarılan ve Türklerin atası olan çocuğun hikayesi." },
      { name: "Türeyiş Destanı", description: "Bir kurt suretindeki tanrıdan türeyen Uygurların başlangıç efsanesi." },
      { name: "Sarıkız Efsanesi", description: "Kaz Dağları'nın zirvesinde yaşayan ve efsanelere konu olan Sarıkız'ın sırrı." },
      { name: "Hezarfen Ahmed Çelebi", description: "Kendi yaptığı kanatlarla Galata Kulesi'nden Üsküdar'a uçan adam ol." },
      { name: "Leyla ile Mecnun", description: "Çöllere düşen Mecnun'un ilahi aşkını ve trajik hikayesini deneyimle." },
      { name: "Lokman Hekim", description: "Ölümsüzlük iksirini arayan ve tüm dertlere deva bulan efsanevi hekim." },
      { name: "Yedi Uyurlar", description: "Putperest bir hükümdardan kaçıp bir mağarada 300 yıl uyuyan gençlerin hikayesi." },
      { name: "Umay Ana", description: "Türk mitolojisindeki doğum ve bereket tanrıçasıyla tanış ve ondan yardım iste." },
      { name: "Oğuz Kağan Destanı", description: "Türklerin büyük atası Oğuz Kağan'ın doğuşunu, evliliklerini ve fetihlerini yaşa." },
      { name: "Alp Er Tunga", description: "Turan'ın efsanevi hükümdarı olarak İranlılarla olan mücadelene liderlik et." },
      { name: "Manas Destanı", description: "Kırgız halkının bu devasa destanında kahraman Manas'ın yerine geç." },
      { name: "Gökbörü Efsanesi", description: "Türklere yol gösteren kutsal kurt ile olan mistik bağı deneyimle." },
      { name: "Hz. Hızır ile Buluşma", description: "Darda kalanlara yardım eden bu gizemli bilgeyle yolların kesişsin." },
      { name: "Yunus Emre", description: "Odun taşıyarak başladığı dergah yolculuğunda büyük bir halk ozanına dönüş." },
      { name: "Karacaoğlan", description: "Güzel Elif'e olan aşkı uğruna diyar diyar gezen halk ozanı ol." },
      { name: "Somuncu Baba", description: "Bursa'da fırıncılık yaparken kerametlerini gizleyen ulu bir evliyanın sırrına ortak ol." },
      { name: "Akdamar Adası Efsanesi", description: "Van Gölü'ndeki adada yaşayan Tamara'ya ulaşmaya çalışan gencin trajik aşkı." },
      { name: "Mevlana ve Şems", description: "Konya'da, Mevlana'nın hayatını değiştiren Şems-i Tebrizi ile olan dostluğu yaşa." },
      { name: "Keloğlan Masalları", description: "Saçı olmasa da aklı ve şansıyla zorlukları aşan bu klasik masal kahramanı ol." },
      { name: "Anka Kuşu (Simurg)", description: "Kaf Dağı'nın ardında yaşayan ve küllerinden yeniden doğan efsanevi kuşu bul." },
      { name: "Ahi Evran", description: "Anadolu'da esnaf teşkilatını kuran bu bilge liderin yanında zanaat öğren." },
      { name: "Demirci Kawa Destanı", description: "Zalim kral Dehak'a karşı isyan başlatan efsanevi demirci ol." },
      { name: "Hz. Süleyman ve Kuşlar", description: "Hayvanların dilini anlayan peygamber kral olarak adaleti sağla." },
      { name: "Deli Dumrul", description: "Azrail'e meydan okuyan ve kendi canı yerine can arayan Dede Korkut kahramanı." },
    ],
  },
  {
    categoryName: "Kitap ve Roman Dünyaları",
    legends: [
      { name: "Yüzüklerin Efendisi", description: "Orta Dünya'yı Sauron'un karanlığından kurtarmak için Tek Yüzük'ü yok et." },
      { name: "Witcher: Son Dilek", description: "Canavar avcısı Rivyalı Geralt olarak ahlaki açıdan gri görevleri tamamla." },
      { name: "Harry Potter ve Felsefe Taşı", description: "Hogwarts'a gelen genç bir büyücü ol ve Lord Voldemort'un planlarını engelle." },
      { name: "Dune: Çöl Gezegeni", description: "Arrakis'in kontrolü için verilen politik ve mistik savaşta Paul Atreides'e katıl." },
      { name: "Taht Oyunları", description: "Westeros'un Yedi Krallığı için verilen entrika dolu savaşta kendi hanedanını zafere taşı." },
      { name: "Sherlock Holmes", description: "Baker Sokağı 221B'de, deha dedektif ile birlikte çözülmesi zor davaları araştır." },
      { name: "Narnia: Aslan, Cadı ve Dolap", description: "Bir dolabın içinden geçerek Narnia'ya ulaş ve Beyaz Cadı'ya karşı savaş." },
      { name: "Açlık Oyunları", description: "Panem'in totaliter rejimine karşı ölümcül bir arenada hayatta kalma mücadelesi ver." },
      { name: "Percy Jackson ve Şimşek Hırsızı", description: "Zeus'un şimşeğini çalmakla suçlanan bir yarı tanrı olarak masumiyetini kanıtla." },
      { name: "Otostopçunun Galaksi Rehberi", description: "Dünya yok edilmeden saniyeler önce bir uzaylıyla otostop çekerek galaksiyi gez." },
      { name: "Ben, Robot", description: "Asimov'un Üç Robot Yasası'nın sınırlarını zorlayan gizemli robot vakalarını çöz." },
      { name: "Fahrenheit 451", description: "Kitapların yakıldığı bir gelecekte, itfaiyeci Guy Montag'ın isyanına tanıklık et." },
      { name: "1984: Büyük Birader", description: "Her şeyi gören Büyük Birader'in totaliter rejiminde düşünce suçu işlemeye çalış." },
      { name: "Cesur Yeni Dünya", description: "Herkesin mutlu olduğu ama kimsenin özgür olmadığı bu teknolojik ütopyayı sorgula." },
      { name: "Frankenstein", description: "Victor Frankenstein'ın yarattığı trajik canavarın hikayesini deneyimle." },
      { name: "Dr. Jekyll ve Mr. Hyde", description: "İnsan doğasının iyi ve kötü yanlarını ayıran deneyi yapan doktor ol." },
      { name: "Drakula", description: "Transilvanya'nın karanlık şatosunda Kont Drakula'nın gizemini çöz." },
      { name: "Don Kişot", description: "Şövalye romanlarından etkilenip kendini şövalye sanan bir asilzadenin maceraları." },
      { name: "Moby Dick", description: "Kaptan Ahab'ın beyaz balina Moby Dick'ten intikam alma takıntısına katıl." },
      { name: "Robinson Crusoe", description: "Issız bir adada tek başına hayatta kalma mücadelesi ver." },
      { name: "Gulliver'in Gezileri", description: "Cüceler ve devler ülkesi dahil olmak üzere fantastik diyarlara yolculuk yap." },
      { name: "İki Şehrin Hikayesi", description: "Fransız Devrimi sırasında Londra ve Paris'te geçen bir aşk ve fedakarlık hikayesi." },
      { name: "Sefiller", description: "Bir somun ekmek çaldığı için kürek cezasına çarptırılan Jean Valjean'ın kaçış hikayesi." },
      { name: "Suç ve Ceza", description: "Fakir bir öğrenci olan Raskolnikov'un işlediği bir cinayetin vicdani yüküyle yüzleş." },
      { name: "Otomatik Portakal", description: "Yakalanıp şiddete karşı beyin yıkama deneyine tabi tutulan bir holigan ol." },
      { name: "Metro 2033", description: "Nükleer savaş sonrası Moskova metrosunda hayatta kalmaya çalışan Artyom'a rehberlik et." },
      { name: "Denizler Altında Yirmi Bin Fersah", description: "Kaptan Nemo'nun denizaltısı Nautilus ile okyanusların derinliklerini keşfet." },
      { name: "Vakıf'ın Kuruluşu", description: "Galaktik bir imparatorluğun çöküşünü öngören Hari Seldon'ın planını devam ettir." },
      { name: "Diskdünya Serüveni", description: "Terry Pratchett'ın dört filin sırtındaki disk şeklindeki dünyasında komik bir maceraya atıl." },
      { name: "Hazine Adası", description: "Genç Jim Hawkins olarak korsanlarla dolu bir adada Kaptan Flint'in hazinesini ara." },
      { name: "İlahi Komedya", description: "Dante Alighieri'ye Cehennem, Araf ve Cennet'ten geçerken rehberlik et." },
      { name: "Varolmanın Dayanılmaz Hafifliği", description: "Sovyet işgali altındaki Prag'da dört karakterin aşk ve hayat felsefelerini keşfet." },
      { name: "Dorian Gray'in Portresi", description: "Kendi yerine portresinin yaşlandığı, sonsuza dek genç kalan bir adamın ahlaki çöküşü." },
      { name: "Usta ve Margarita", description: "Şeytan'ın 1930'lar Moskova'sını ziyaret etmesiyle başlayan büyülü ve satirik bir hikaye." },
    ],
  },
  {
    categoryName: "Efsanevi Film Evrenleri",
    legends: [
      { name: "Star Wars: Yeni Bir Umut", description: "Güç'ü keşfeden genç bir çiftçi olarak Ölüm Yıldızı'nı yok etme görevine katıl." },
      { name: "The Matrix", description: "Gerçekliğin bir simülasyon olduğunu keşfeden Neo ol ve makinelere karşı isyan başlat." },
      { name: "Blade Runner", description: "Geleceğin Los Angeles'ında insanlardan ayırt edilemeyen kaçak 'replicant'ları avla." },
      { name: "Jurassic Park", description: "Klonlanmış dinozorların olduğu bir adada, işler ters gidince hayatta kalmaya çalış." },
      { name: "Indiana Jones: Kutsal Hazine", description: "Efsanevi Ahit Sandığı'nı Nazilerden önce bulmak için dünyayı dolaş." },
      { name: "Geleceğe Dönüş", description: "Bir DeLorean zaman makinesiyle geçmişe gidip kendi varlığını tehlikeye at." },
      { name: "Gladyatör", description: "İhanete uğrayan bir Roma generali olarak arenada savaşıp imparatordan intikam al." },
      { name: "Karayip Korsanları", description: "Kaptan Jack Sparrow ile lanetli bir hazinenin ve ölümsüz korsanların peşine düş." },
      { name: "Mad Max: Öfkeli Yollar", description: "Kıyamet sonrası bir çölde, zalim bir tirandan kaçan bir grup isyancıya yardım et." },
      { name: "Yaratık (Alien)", description: "Uzayın derinliklerinde, Nostromo gemisinin mürettebatıyla birlikte ölümcül bir yaratıktan kurtul." },
      { name: "Terminatör 2: Mahşer Günü", description: "Gelecekten gelen bir Terminatör olarak genç John Connor'ı T-1000'den koru." },
      { name: "Başlangıç (Inception)", description: "İnsanların rüyalarına girerek fikir çalan veya eken bir grup uzmanın parçası ol." },
      { name: "John Wick", description: "Emekli bir tetikçi olarak, köpeğini öldürenlerden intikam almak için yeraltı dünyasına geri dön." },
      { name: "V for Vendetta", description: "Maskeli bir anarşist olarak faşist bir İngiliz hükümetine karşı devrim başlat." },
      { name: "Parazit", description: "Zengin bir ailenin hayatına sızan fakir bir ailenin ferdi olarak planı sürdür." },
      { name: "Kuzuların Sessizliği", description: "Bir seri katili yakalamak için dahi bir yamyam olan Hannibal Lecter'dan yardım al." },
      { name: "The Godfather", description: "Corleone mafya ailesinin bir üyesi olarak yüksel ve ailenin işlerini yönet." },
      { name: "Ucuz Roman (Pulp Fiction)", description: "Los Angeles'ın yeraltı dünyasında, yolları kesişen iki tetikçiden biri ol." },
      { name: "Esaretin Bedeli", description: "Shawshank hapishanesinde masumiyetini ve umudunu korumaya çalışan bir mahkum ol." },
      { name: "Kara Şövalye", description: "Batman olarak, Gotham şehrini anarşiye sürüklemeye çalışan Joker'i durdur." },
      { name: "Avatar", description: "Pandora'nın yerli halkı Na'vi'nin bedenine zihnini aktaran bir asker olarak taraf seç." },
      { name: "Guguk Kuşu", description: "Bir akıl hastanesinde, zalim baş hemşireye karşı diğer hastalara liderlik et." },
      { name: "Dövüş Kulübü", description: "Uykusuzluk çeken bir ofis çalışanı olarak, medeniyetin kurallarını yıkan bir kulüp kur." },
      { name: "Yıldızlararası (Interstellar)", description: "İnsanlık için yeni bir yuva aramak üzere solucan deliğinden geçen bir grup astronota katıl." },
      { name: "Cehenneme Bir Adım (Apocalypse Now)", description: "Vietnam Savaşı'nda, aklını kaçırmış bir albayı bulup yok etme görevini üstlen." },
      { name: "Gattaca", description: "Genetik olarak 'kusurlu' doğduğun bir gelecekte, kimliğini değiştirerek uzay görevine katılmaya çalış." },
      { name: "Truman Show", description: "Tüm hayatının bir reality show olduğunu fark et ve bu sahte dünyadan kaçmaya çalış." },
      { name: "Forrest Gump", description: "Düşük IQ'lu ama altın kalpli bir adam olarak 20. yüzyıl Amerikan tarihinin önemli anlarına tanıklık et." },
      { name: "Köstebek (The Departed)", description: "Polisin içine sızmış bir gangster veya mafyanın içine sızmış bir polis olarak hayatta kal." },
      { name: "Parfüm: Bir Katilin Hikayesi", description: "Mükemmel kokuyu yaratmak için cinayet işleyen Jean-Baptiste Grenouille'in izini sür." },
      { name: "Amelie", description: "Paris'te yaşayan ve etrafındaki insanların hayatlarına sihirli dokunuşlar yapan hayalperest bir kız ol." },
      { name: "Soysuzlar Çetesi (Inglourious Basterds)", description: "İşgal altındaki Fransa'da Nazileri avlayan bir grup Yahudi-Amerikan askerine katıl." },
      { name: "Oldboy (İhtiyar Delikanlı)", description: "15 yıl sebepsizce hapsedildikten sonra serbest bırakılan bir adam olarak intikamını al." },
      { name: "Zindan Adası (Shutter Island)", description: "Bir akıl hastanesinin bulunduğu adadaki bir kayıp vakasını araştıran bir dedektif ol." },
    ]
  },
  {
    categoryName: "Korku ve Şehir Efsaneleri",
    legends: [
      { name: "Cthulhu'nun Çağrısı", description: "H.P. Lovecraft'ın kozmik korku dünyasında aklını kaybetmeden hayatta kal." },
      { name: "Slender Man", description: "Ormanda gizlenen bu modern efsaneden kanıt topla ve kaç." },
      { name: "13. Cuma", description: "Crystal Lake kampında maskeli katil Jason Voorhees'ten kurtul." },
      { name: "Wendigo", description: "Kuzey Amerika ormanlarında, insan yiyen bu korkunç yaratıktan saklan." },
      { name: "Gulyabani", description: "Osmanlı'nın karanlık konaklarında ve çöllerinde gezinen bu hortlakla yüzleş." },
      { name: "Bloody Mary", description: "Aynanın karşısına geç ve üç kez adını söylemeye cesaret et." },
      { name: "Mothman", description: "Batı Virjinya'da felaketleri haber veren bu kanatlı, kırmızı gözlü yaratığı araştır." },
      { name: "Kurt Adam Laneti", description: "Dolunayda dönüşen bu trajik canavarın lanetini kırmaya çalış." },
      { name: "Başsız Süvari", description: "Sleepy Hollow kasabasında geceleri dört nala koşan bu hayaletten kaç." },
      { name: "Halka (The Ring)", description: "İzleyenleri 7 gün sonra öldüren lanetli video kasetinin gizemini çöz." },
      { name: "Blair Cadısı", description: "Maryland ormanlarında kaybolan film öğrencilerinin ardındaki laneti araştır." },
      { name: "Skinwalker", description: "Navajo kültüründeki şekil değiştiren bu korkunç büyücüyle yüzleş." },
      { name: "Chupacabra", description: "Latin Amerika'da hayvanlara saldıran bu efsanevi yaratığın izini sür." },
      { name: "Jeff the Killer", description: "İnternetin karanlık köşelerinden doğan bu Creepypasta karakterinden saklan." },
      { name: "Krampus", description: "Noel zamanı yaramaz çocukları cezalandıran bu şeytani folklorik yaratıktan kaç." },
      { name: "Dybbuk Kutusu", description: "İçinde huzursuz bir ruh barındırdığı söylenen lanetli bir şarap dolabını aç." },
      { name: "Polybius", description: "Oyuncularını deliliğe sürüklediği söylenen efsanevi atari oyununu bul ve oyna." },
      { name: "Cinnet (The Shining)", description: "Kışın kapalı olan Overlook Oteli'nde aklını yitiren bir babadan kaç." },
      { name: "Elm Sokağında Kâbus", description: "Rüyalarında insanları avlayan Freddy Krueger'dan uyanık kalarak kurtul." },
      { name: "Şeytan (The Exorcist)", description: "İçine şeytan girmiş küçük bir kıza yardım etmeye çalışan bir rahip ol." },
      { name: "Teksas Katliamı", description: "Teksas'ın kırsalında yamyam bir ailenin eline düşen gençlerden biri ol." },
      { name: "Nosferatu", description: "Almanya'ya veba ve korku getiren bu ilk vampir efsanesiyle yüzleş." },
      { name: "Garez (The Grudge)", description: "Lanetli bir evde ölenlerin öfkeli ruhlarından (Onryō) kurtulmaya çalış." },
      { name: "Annabelle", description: "Lanetli olduğu söylenen porselen bir bebekle aynı evde hayatta kal." },
      { name: "O (It)", description: "Derry kasabasının çocuklarını avlayan palyaço şeklindeki Pennywise ile savaş." },
      { name: "Zombi Salgını", description: "George A. Romero'nun dünyasında, yaşayan ölülerin istila ettiği bir dünyada hayatta kal." },
      { name: "Siren Kafa (Siren Head)", description: "İki sirenli, uzun ve iskeletimsi bu modern canavarın olduğu ormandan kaç." },
      { name: "Rus Uyku Deneyi", description: "Uyumanın engellendiği bir deneyde deliren deneklerin olduğu laboratuvardan kurtul." },
      { name: "Kara Gözlü Çocuklar", description: "Evine veya arabana girmek isteyen tamamen siyah gözlü bu ürkütücü çocuklarla karşılaş." },
      { name: "Doppelgänger", description: "Tıpatıp sana benzeyen ve yerini almaya çalışan bu kötücül kopyadan kurtul." },
      { name: "Gölge İnsanlar", description: "Gözünün ucuyla gördüğün bu karanlık, insansı figürlerin sırrını çöz." },
      { name: "Tekinsiz Vadi", description: "İnsana çok benzeyen ama tam olarak insan olmayan android veya robotların olduğu bir tesisten kaç." },
      { name: "Sessiz Tepe (Silent Hill)", description: "Sisli ve tekinsiz bir kasabada, kendi korkularınla ve canavarlarla yüzleş." },
      { name: "Hayvan Mezarlığı", description: "Ölüleri geri getiren bir mezarlığa gömdüğün sevdiklerinin dönüşüyle başa çık." },
    ],
  },
   {
    categoryName: "Peri Masalları",
    legends: [
        { name: "Kırmızı Başlıklı Kız", description: "Büyükannesine giderken ormandaki kötü kurda karşı dikkatli ol." },
        { name: "Hansel ve Gretel", description: "Ormanda kaybolduktan sonra şekerden yapılmış cadı evinden kaç." },
        { name: "Pamuk Prenses", description: "Kötü kraliçeden kaç, yedi cücelerle tanış ve zehirli elmaya dikkat et." },
        { name: "Külkedisi (Cinderella)", description: "Büyülü balkabağı arabasıyla baloya git, ama gece yarısından önce dönmelisin." },
        { name: "Uyuyan Güzel", description: "Yüz yıllık uykusuna dalan prensesi kötücül büyüden kurtar." },
        { name: "Rapunzel", description: "Kuleye hapsedilmiş uzun saçlı prensesi kurtarmak için zekanı kullan." },
        { name: "Jack ve Fasulye Sırığı", description: "Sihirli fasulyelerle gökyüzündeki devler ülkesine tırman." },
        { name: "Çizmeli Kedi", description: "Zeki bir kedinin yardımıyla yoksul bir değirmencinin oğluna yardım et." },
        { name: "Güzel ve Çirkin", description: "Babasını kurtarmak için bir canavarın şatosunda yaşamayı kabul et." },
        { name: "Alaaddin'in Sihirli Lambası", description: "Sihirli bir lamba bul, cini serbest bırak ve üç dilek hakkını kullan." },
        { name: "Ali Baba ve Kırk Haramiler", description: "'Açıl susam açıl' diyerek gizli bir hazine mağarasına gir." },
        { name: "Kurşun Asker", description: "Tek bacaklı bir kurşun askerin balerine olan aşkı ve maceraları." },
        { name: "Kibritçi Kız", description: "Soğuk bir yılbaşı gecesinde kibrit satarak hayaller kuran fakir bir kız ol." },
        { name: "Bremen Mızıkacıları", description: "Sahiplerinden kaçan dört hayvanın Bremen'e gidip müzisyen olma hayali." },
        { name: "Parmak Kız", description: "Bir çiçekten doğan ve başparmak büyüklüğünde olan kızın maceraları." },
        { name: "Altın Saçlı Kız ve Üç Ayı", description: "Ormandaki bir kulübede üç ayının yemeğini yiyip yatağında uyu." },
        { name: "Kurt ile Yedi Keçi Yavrusu", description: "Annenin sözünü dinle ve kurda kapıyı açma." },
        { name: "Pinokyo", description: "Yalan söyledikçe burnu uzayan bir kukla olarak gerçek bir çocuk olmaya çalış." },
        { name: "Küçük Deniz Kızı", description: "Aşık olduğu prens için sesini feda edip insan olan bir denizkızının hikayesi." },
        { name: "Karlar Kraliçesi", description: "Arkadaşı Kay'ı kurtarmak için Karlar Kraliçesi'nin buzdan sarayına giden Gerda'ya yardım et." },
        { name: "Çirkin Ördek Yavrusu", description: "Farklı olduğu için dışlanan bir yavrunun aslında bir kuğu olduğunu keşfetme yolculuğu." },
        { name: "Rumpelstiltskin", description: "Samanı altına çevirebilen bu gizemli cücenin adını tahmin etmeye çalış." },
        { name: "İmparatorun Yeni Giysileri", description: "Sadece akıllıların görebildiği söylenen sihirli giysileri giyen imparatorun hikayesi." },
        { name: "Prenses ve Bezelye Tanesi", description: "Yirmi yatağın altındaki bir bezelye tanesini hissederek gerçek bir prenses olduğunu kanıtla." },
        { name: "Fareli Köyün Kavalcısı", description: "Kavalıyla fareleri ve sonra çocukları peşinden sürükleyen gizemli adam." },
        { name: "Mavi Sakal", description: "Zengin ve gizemli bir adamla evlenen genç bir kadının, kocasının yasak odasının sırrını çözme çabası." },
        { name: "Sindbad'ın Maceraları", description: "Binbir Gece Masalları'nın bu kahramanıyla yedi tehlikeli deniz yolculuğuna çık." },
        { name: "On iki Dans Eden Prenses", description: "Her gece ayakkabıları eskiyene kadar nerede dans ettiklerini gizlice öğren." },
        { name: "Balıkçı ve Karısı", description: "Dilek tutan sihirli bir balık yakalayan ama karısının açgözlülüğüyle her şeyi kaybeden balıkçı." },
        { name: "Kurbağa Prens", description: "Büyüyle kurbağaya dönüştürülmüş bir prensi, verdiğin sözü tutarak kurtar." },
        { name: "Kaz Çobanı Kız", description: "Kötü hizmetçisi tarafından yeri alınan gerçek prensesin hakkını geri almasına yardım et." },
        { name: "Demir Hans", description: "Ormanda yaşayan vahşi bir adam tarafından büyütülen bir prensin kahramanlıkları." },
        { name: "Bülbül", description: "Çin imparatorunu mekanik bir bülbül yerine gerçek bir bülbülün kurtarması." },
        { name: "Üç Küçük Domuzcuk", description: "Evlerini kurttan korumak için saman, çalı ve tuğladan evler yapan kardeşler." },
    ],
  },
  {
    categoryName: "Tarihi ve Folklorik",
    legends: [
      { name: "Kral Arthur ve Yuvarlak Masa", description: "Camelot'un efsanevi kralı ol, Excalibur'u bul ve krallığını birleştir." },
      { name: "Robin Hood", description: "Sherwood Ormanı'nda zenginden alıp fakire veren kanun kaçağı ol." },
      { name: "El Dorado'nun Peşinde", description: "Amazon ormanlarının derinliklerindeki kayıp altın şehri ara." },
      { name: "Kleopatra'nın Son Günleri", description: "Mısır'ın son kraliçesi olarak Roma'ya karşı politik bir savaş ver." },
      { name: "Jeanne d'Arc'ın Yükselişi", description: "Fransa'yı kurtarmak için ilahi sesler duyan genç bir köylü kızına liderlik et." },
      { name: "Spartacus İsyanı", description: "Romalı bir gladyatör olarak köle isyanına liderlik et." },
      { name: "Mulan Efsanesi", description: "Babasının yerine erkek kılığına girerek Hunlara karşı savaş." },
      { name: "William Wallace", description: "İskoçya'nın bağımsızlığı için 'Cesur Yürek' olarak İngiltere'ye isyan et." },
      { name: "Cengiz Han'ın Yükselişi", description: "Dağınık Moğol kabilelerini birleştirerek tarihin en büyük imparatorluğunu kur." },
      { name: "Haşhaşiler ve Alamut Kalesi", description: "Hasan Sabbah'ın fedailerinden biri olarak gizli görevlere katıl." },
      { name: "Kayıp Roma Lejyonu", description: "Part İmparatorluğu'nda kaybolan efsanevi 9. Lejyon'un akıbetini araştır." },
      { name: "Kristof Kolomb'un Yolculuğu", description: "Hindistan'a yeni bir yol ararken 'Yeni Dünya'yı keşfeden kaptan ol." },
      { name: "Samurayın Yolu", description: "Feodal Japonya'da onurunu korumaya çalışan bir samuray veya efendisiz kalmış bir ronin ol." },
      { name: "Vikingler: Vinland Saga", description: "Leif Erikson ile birlikte Grönland'dan yola çıkarak Kolomb'dan önce Amerika'yı keşfet." },
      { name: "Kara Veba", description: "Avrupa'yı kasıp kavuran bu korkunç salgının ortasında bir doktor veya hırsız olarak hayatta kal." },
      { name: "Tapınak Şövalyeleri", description: "Kutsal Topraklar'da savaşan bu gizemli tarikatın bir üyesi ol ve Kutsal Kase'yi ara." },
      { name: "İpek Yolu Macerası", description: "Çin'den Venedik'e uzanan bu tehlikeli ticaret yolunda bir kervanla seyahat et." },
      { name: "Büyük İskender", description: "Makedonyalı genç kral olarak bilinen dünyanın büyük bir kısmını fethet." },
      { name: "Hannibal'in Alpleri Geçişi", description: "Kartacalı komutan olarak, fillerle Alpleri aşarak Roma'ya meydan oku." },
      { name: "Jül Sezar'ın Suikastı", description: "Roma'nın diktatörü olarak komplolarla dolu senatoda hayatta kalmaya çalış." },
      { name: "Kazıklı Voyvoda", description: "Osmanlı'ya karşı Eflak'ı savunan Vlad Tepeş'in acımasız yöntemlerini kullan." },
      { name: "Kaptan Karasakal", description: "Karayipler'in en korkulan korsanı olarak gemilere saldır ve hazineler biriktir." },
      { name: "Billy the Kid", description: "Vahşi Batı'da genç bir kanun kaçağı olarak şeriflerden ve ödül avcılarından kaç." },
      { name: "Wyatt Earp ve OK Corral", description: "Tombstone kasabasında bir kanun adamı olarak efsanevi silahlı çatışmaya katıl." },
      { name: "Anastasia'nın Gizemi", description: "Bolşevik devriminden kurtulduğu söylenen Rus prensesi olduğunu kanıtlamaya çalış." },
      { name: "Mansa Musa'nın Haccı", description: "Tarihin en zengin insanı olarak Mali'den Mekke'ye altın dağıttığın yolculuğa çık." },
      { name: "Piri Reis'in Haritası", description: "Antarktika'yı bile gösterdiği söylenen bu gizemli haritanın sırlarını çöz." },
      { name: "Amelia Earhart'ın Kayboluşu", description: "Uçağıyla dünyayı dolaşırken Pasifik Okyanusu'nda kaybolan pilotun son anları." },
      { name: "Roswell Vakası", description: "1947'de New Mexico'ya düştüğü söylenen UFO enkazını ve uzaylıları araştır." },
      { name: "Machu Picchu'nun Keşfi", description: "And Dağları'nda kayıp İnka şehrini arayan bir kaşif ol." },
      { name: "Pompei'nin Son Günü", description: "Vezüv Yanardağı patlarken bu Roma şehrinden kaçmaya çalış." },
      { name: "Vikinglerin İngiltere Akınları", description: "Lindisfarne manastırına baskın yapan ilk Vikinglerden biri ol." },
      { name: "Haçlı Seferleri", description: "Kutsal Toprakların kontrolü için bir şövalye veya bir Selahaddin askeri olarak savaş." },
      { name: "Moğol İstilası", description: "Cengiz Han'ın ordularına karşı bir kaleyi veya şehri savun." },
    ],
  },
  {
    categoryName: "Eski Tanrı Hikayeleri",
    legends: [
      { name: "Zeus ve Titanlar Savaşı", description: "Olympos tanrılarına liderlik ederek babası Kronos ve Titanlara karşı isyan et." },
      { name: "Odin'in Gözü", description: "Mimir'in bilgelik kuyusundan içmek ve dokuz diyarın sırrını öğrenmek için gözünü feda et." },
      { name: "Ra'nın Yeraltı Yolculuğu", description: "Güneş tanrısı Ra olarak, her gece yeraltı dünyasından geçerek kaos yılanı Apep ile savaş." },
      { name: "Loki'nin Hileleri", description: "İskandinav hile tanrısı olarak, tanrıları kandır, şekil değiştir ve Ragnarok'u tetikle." },
      { name: "Persephone'nin Kaçırılışı", description: "Yeraltı kralı Hades tarafından kaçırılan bahar tanrıçası ol ve mevsimlerin başlangıcına neden ol." },
      { name: "Thor'un Çekici Mjolnir", description: "Buz devlerine karşı en güçlü silahın olan Mjolnir'i cücelerden geri al." },
      { name: "Anubis ve Ölülerin Yargılanması", description: "Mısır'ın ölüler tanrısı olarak, ölen ruhların kalplerini hakikat tüyüyle tart." },
      { name: "Cernunnos, Vahşi Tanrı", description: "Keltlerin boynuzlu orman tanrısı olarak doğa ve hayvanlar üzerinde hüküm sür." },
      { name: "Morrigan'ın Kehanetleri", description: "İrlanda'nın savaş, kader ve ölüm tanrıçası olarak savaşların sonucunu belirle." },
      { name: "Marduk ve Tiamat", description: "Babil yaratılış destanında, kaosun ejderha tanrıçası Tiamat'ı yenerek evreni düzene sok." },
      { name: "İnanna'nın Yeraltına İnişi", description: "Sümer aşk ve savaş tanrıçası olarak, kız kardeşi Ereshkigal'in hükmettiği ölüler diyarına yolculuk yap." },
      { name: "Quetzalcoatl'ın Gidişi", description: "Azteklerin tüylü yılan tanrısı olarak, halkına veda edip bir gün döneceğine söz ver." },
      { name: "Huitzilopochtli ve Ay'ın Katli", description: "Aztek güneş ve savaş tanrısı olarak doğduğun anda sana pusu kuran 400 kardeşinle savaş." },
      { name: "Dagda'nın Kazanı", description: "İrlanda tanrılarının babası olarak, hiç boşalmayan sihirli kazanını kötülükten koru." },
      { name: "Kelt Öteyurdu (Tir na nOg)", description: "Ölümsüz gençliğin diyarına yolculuk eden bir ölümlü ol, ama geri dönmenin bir bedeli var." },
      { name: "Druidlerin Ritüelleri", description: "Kutsal meşe korularında, doğanın ve eski tanrıların gücünü kullanan bir Kelt rahibi ol." },
      { name: "Baal ve Mot'un Savaşı", description: "Kenan tanrısı Baal olarak, kuraklık ve ölüm tanrısı Mot'u yenerek topraklara yeniden bereket getir." },
      { name: "Taranis, Gök Gürültüsü Tanrısı", description: "Galya'nın Jüpiter'e benzeyen tanrısı olarak, fırtınaları yönet ve kutsal tekerleğini kullan." },
      { name: "Epona, Atların Tanrıçası", description: "Romalıların bile taptığı bu Galya tanrıçası olarak atlara ve yolculara rehberlik et." },
      { name: "Veles ve Perun Çatışması", description: "Slav mitolojisinde, yeraltının boynuzlu tanrısı Veles olarak gök tanrısı Perun ile savaş." },
      { name: "Baba Yaga'nın Kulübesi", description: "Tavuk bacakları üzerinde duran kulübesinde yaşayan bu gizemli ve tehlikeli Slav cadısıyla karşılaş." },
      { name: "Kupala Gecesi Ritüeli", description: "Yaz gündönümünde, ormanın derinliklerinde sihirli eğrelti otu çiçeğini ara." },
      { name: "Prometheus'un Ateşi", description: "İnsanlığa ateşi çalarak bilgeliği hediye eden ve bunun için sonsuza dek cezalandırılan Titan ol." },
      { name: "Pan ve Syrinx", description: "Kırların ve müziğin tanrısı Pan olarak, aşkından kaçan su perisi Syrinx'i takip et." },
      { name: "Dionysos ve Mainadlar", description: "Şarap ve coşku tanrısı olarak, kendinden geçmiş takipçilerinle birlikte vahşi kutlamalara liderlik et." },
      { name: "Apollo ve Daphne", description: "Aşk tanrısı Eros tarafından lanetlenen Apollo olarak, senden kaçıp bir defne ağacına dönüşen periyi izle." },
      { name: "Artemis ve Actaeon", description: "Av tanrıçası Artemis'i çıplak gören ve geyiğe dönüştürülerek kendi köpekleri tarafından parçalanan avcı ol." },
      { name: "Hephaistos'un İntikamı", description: "Olympos'tan atılan demirci tanrı olarak, Hera için yaptığın tuzaklı taht ile intikamını al." },
      { name: "Demeter ve Persephone", description: "Kızı yeraltına kaçırılan tarım tanrıçası olarak, yeryüzüne kışı ve kıtlığı getir." },
      { name: "Baldur'un Ölümü", description: "İskandinav tanrılarının en sevdiği, ölümsüz olduğu sanılan Baldur'u Loki'nin hilesinden koru." },
      { name: "Tyr ve Fenrir", description: "Dev kurt Fenrir'i zincirlemek için tanrıların cesaret edemediği şeyi yap ve elini feda et." },
      { name: "Heimdall ve Bifrost Köprüsü", description: "Asgard'ın bekçisi olarak, devlerin istilasını haber vermek için Gjallarhorn'u çal." },
      { name: "Freya'nın Kolyesi Brisingamen", description: "Aşk ve güzellik tanrıçası olarak, bu değerli kolyeyi elde etmek için cücelerle pazarlık yap." },
      { name: "Inti, İnka Güneş Tanrısı", description: "İnka imparatorluğunun atası olarak, halkına medeniyet ve tarımı öğret." },
      { name: "Pachamama, Toprak Ana", description: "And Dağları'nın bu cömert ama öfkeli tanrıçasına sunular sunarak bereket dile." },
      { name: "Blodeuwedd'in İhaneti", description: "Gal mitolojisinde, çiçeklerden yaratılan ve kocasını aldatan kadının baykuşa dönüşme hikayesi." },
      { name: "Mannanan mac Lir", description: "İrlanda deniz tanrısı olarak, sisli pelerininle diyarları gizle ve sihirli geminle yolculuk et." },
      { name: "Arawn, Annwn'un Kralı", description: "Gal mitolojisindeki yeraltı dünyasının kralı olarak, bir ölümlüyle bir yıllığına yer değiştir." },
      { name: "Ukko, Fin Gök Tanrısı", description: "Finlandiya'nın baş tanrısı olarak, şimşekler çaktırarak ve yağmur yağdırarak dünyaya hükmet." },
      { name: "Ziusudra'nın Tufanı", description: "Sümerlerin tufan kahramanı olarak, tanrı Enki'nin uyarısıyla bir gemi inşa et ve hayatta kal." },
    ]
  },
];